name: 02 Evento Issue
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '*.md'
  issues:
      types:
      - opened
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "¡Hola Mundo!"